version: 2
jobs:
  install:
    docker:
    - image: circleci/node:9.6
    working_directory: ~/repo
    steps:
    - checkout
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
  build:
    docker:
    - image: circleci/node:9.6
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn build-css
    - run: yarn build-js
    - persist_to_workspace:
        root: ~/repo
        paths: src
  test:
    docker:
    - image: circleci/node:9.6
    working_directory: ~/repo
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn test
  deploy_to_production:
    docker:
    - image: circleci/node:9.6
    working_directory: ~/repo
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn firebase use production --token=$FIREBASE_DEPLOY_TOKEN_PRODUCTION
    - run: yarn firebase deploy --token=$FIREBASE_DEPLOY_TOKEN_PRODUCTION
  # deploy_to_staging:
  #   docker:
  #   - image: circleci/node:9.6
  #   working_directory: ~/repo
  #   steps:
  #   - attach_workspace:
  #       at: ~/repo
  #   - restore_cache:
  #     keys:
  #     - v1-dependencies-{{ checksum "package.json" }}
  #     - v1-dependencies-
  #   - run: |
  #       if [[ `git branch` ]]
  #   - run: yarn firebase use staging
  #   - run: yarn firebase deploy --token=$FIREBASE_DEPLOY_TOKEN_STAGING
  deploy_to_development:
    docker:
    - image: circleci/node:9.6
    working_directory: ~/repo
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn firebase use development --token=$FIREBASE_DEPLOY_TOKEN_DEVELOPMENT
    - run: yarn firebase deploy --token=$FIREBASE_DEPLOY_TOKEN_DEVELOPMENT
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
    - install
    - build:
        requires:
        - install
    - test:
        requires: 
        - build
    - hold:
        type: approval
        requires:
        - test
        filters:
          branches:
            only:
            - master
    - deploy_to_production:
        requires:
        - hold
        filters:
          branches:
            only: master
    - deploy_to_development:
        requires:
        - test
        filters:
          branches:
            ignore: master